### ISSUE TITLE
Spring Boot autoconfiguration support

### ISSUE THREAD

**Issue by sandor-nemeth** [ryantenney/metrics-spring#131]
I think it would be a good idea to create a Spring Boot based configuration on this project to support spring boot's autoconfiguration. I could do the work along with the tests, however I'd like to know if there is any will to do it in this project, or should I create a new project which only acts as a Spring Boot based wrapper around this library.

**Comment by ryantenney** [comment]
My understanding was that this supports Spring Boot, since it allows Java annotation based config.  Could you please elaborate?  I would be open to further supporting Spring Boot, provided it doesn't require too much in the way of changes to the core project.

**Comment by sandor-nemeth** [comment]
I have to apologise, the issue title is a little bit misleading, I rename that to Spring Boot Autoconfiguration support. 

I meant providing proper auto-configuration classes based on the standard Spring Boot configuration. 

For example only with the configuration below (and including the metrics-spring project) one could 
use the library without any additional configuration effort required. 

```yml
spring:
  metrics: 
    jvm: disabled
    reporter:
      graphite:
        url: http://graphite.url
        port: 2003
        prefixedWith: someprefix
        rates: seconds
        durations: milliseconds
        filter: all
        start:
          period: 1
          timeunit: seconds
        transport: 
          type: rabbitmq
...
```

Also for example it could be possible that if the metrics-jetty or metrics-jvm libraries are on the classpath, then they are by default configured automatically (which can be a sensible default), however the users would be able to disable them by either configuration, or by removing the dependency from the classpath.
