### ISSUE TITLE
configuration via yml files (& profiles)?

### ISSUE THREAD

**Issue by hartmut-pq** [ryantenney/metrics-spring#190]
Hi,

I was wondering if configuration is supported similar to mentioned here:
https://github.com/jdamick/dropwizard-metrics-cloudwatch

```
metrics:
  reporters:
    - type: cloudwatch
      namespace: some_namespace
      globalDimensions:
        - env=dev  # for example
      awsSecretKey: <optional>
      awsAccessKeyId: <optional>
      awsRegion: <optional: region name to use for cloudwatch reporting>
```

-> e.g. to configure a console reporter via application properties, using yaml profile configurations like this?

```
metrics:
  reporters:
    - type: console
```

As I can see there are existing Parsers, .. for the xml bean processing - shouldn't be too complicated to register beans based on app properties as well, right? 

Are pull requests welcome? (I can see lot's of open ones..)
I would be happy to contribute but I'm not quite clear where to start. Any hints?

Allowing to configure reporters via spring profiles would make staging, ... much easier - allowing to configure / add different types and configurations of reporters easily for different profiles...

Thanks
